[AUGMENTATION]
include_augmented = True
smart_aug_csv     = /kaggle/input/datasets/v18hub/intraoral-lesion/SMART_II_AUGMENT/SMART_II_AUGMENT/augment_smart_patient_metadata.csv
smartom_aug_csv   = /kaggle/input/datasets/v18hub/intraoral-lesion/SMART_OM_AUGMENT/SMART_OM_AUGMENT/augment_smartom_patient_metadata.csv

[TRAINING]
# background + DT + LB + RB + UL + UA + VT + LL = 8
num_classes        = 8
epochs             = 10
batch_size         = 2
backbone_lr        = 0.0001
head_lr            = 0.001
momentum           = 0.9
weight_decay       = 0.0005
gradient_clip      = 1.0

val_split          = 0.15
test_split         = 0.15

pretrained_weights = COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
num_workers        = 0
min_lr             = 0.00025
max_iter           = 300
score_threshold    = 0.50
mask_threshold     = 0.30
log_every          = 10
val_every          = 2
checkpoint_period  = 500
images_per_batch   = 2

[SAMPLER]
weighted_sampler    = True
oversample_minority = False

[MODEL]
backbone   = resnet50_fpn
pretrained = True

[SYSTEM]
device      = cuda
num_workers = 0
seed        = 42

[LOGGING]
save_best_model  = True
save_every_epoch = True

[PATHS]
csv.path = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\data\coco\smart_merged_with_coco.csv
images_dir          = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\data
json_dir            = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\data\coco
coco_dir            = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\data\coco
model_dir           = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\models
roi_output_dir      = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\roi_crops
infer_output_dir    = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\inference_output
output_dir          = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\maskrcnn_training
zeroshot_output_dir = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\zeroshot
checkpoint_dir      = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\outputs\mask_rcnn\checkpoint
log_file            = C:\Users\ASUS\OneDrive\Desktop\intra_oral_ml\logs\maskrcnn.log

[DATASET]
val_split      = 0.15
random_seed    = 42
# Ignore polygons smaller than this area (pixels²) — filters out artefacts
min_area       = 10000
normal_dataset = SMART_II
# other options: SMART_OM or BOTH

[ROI]
roi_size         = 224
roi_background   = black
save_mask_overlay = true
score_min_roi    = 0.60

[VISUAL]
visualize_coco = False

[STAGES]
stages = prepare,zero_shot,train,evaluate,inference