[LOGGER]
logger.filename=log_config.ini

[SMART-II-DATAPATH]
smart.basepath=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART II Dataset/SMART II Dataset
smart.normal=Normal
smart.variation=Variation
smart.opmd=OPMD
smart.patient.metadata=Patient-Metadata-SMART-SMITA.xlsx
smart.patient.clean.metadata.filename=/kaggle/working/intraoral_lesion/data/smart/patient_metadata/clean_smart_patient_data.csv
smart.patient.missing.filename=/kaggle/working/intraoral_lesion/data/smart/patient_metadata/smart_column_missing_report.csv

[SMART-OM-DATAPATH]
smartom.basepath=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART-OM/SMART-OM
smartom.metadata.file=Metadata/Patient_s Metadata.xlsx
smartom.normal=01. Normal
smartom.variation=02. Variation from normal
smartom.opmd=03. OPMD
smartom.folders=01. Unannotated
smartom.json.folder=03. Full annotation
smartom.regions=01. Dorsal tongue,02. Ventral tongue,03. Left buccal mucosa,04. Right buccal mucosa,05. Upper lip,06. Lower lip,07. Upper arch,08. Lower arch
smartom.patient.clean.metadata.filename=/kaggle/working/intraoral_lesion/data/smartom/patient_metadata/clean_smartom_patient_data.csv
smartom.patient.missing.filename=/kaggle/working/intraoral_lesion/data/smartom/patient_metadata/smartom_column_missing_report.csv
smartom.descriptor.filename=Descriptors/03. Descriptors_for_lesion_annotation.xlsx
#,04. Lesion annotation,02. Region annotation

[AUGMENT_SMART]
augment.config=/kaggle/working/intraoral_lesion/config/augmentation_smart_config.py
augment.baseroot=/kaggle/working/intraoral_lesion/data/SMART_II_AUGMENT
augment.patient.metadata.filename=augment_smart_patient_metadata.csv
augment.patient.coco.metadata.filename=augment_smart_coco_patient_metadata.csv
augment.labels=opmd,variation
augment.count.opmd=4
augment.count.variation=4

[AUGMENT_SMARTOM]
augment.config=/kaggle/working/intraoral_lesion/config/augmentation_smartom_config.py
augment.baseroot=/kaggle/working/intraoral_lesion/data/SMART_OM_AUGMENT
augment.patient.metadata.filename=augment_smartom_patient_metadata.csv
augment.patient.coco.metadata.filename=augment_smartom_coco_patient_metadata.csv
augment.labels=opmd,variation
augment.count.opmd=4
augment.count.variation=4

[AUGMENT]
augment=BOTH
# Other values for augment can be SMARTOM, SMART

[VALIDATE]
validate.smart.patient.report=/kaggle/working/intraoral_lesion/data/smart/validation/smart_patient_metadata_validation.xlsx
validate.smartom.patient.report=/kaggle/working/intraoral_lesion/data/smartom/validation/smartom_patient_metadata_validation.xlsx

[SMART_MERGED]
smart.merged.basepath=/kaggle/working/intraoral_lesion/data/smart_merged
merged.output.filename=patient_metadata/smart_merged.csv
merged.coco.output.filename=patient_metadata/smart_coco_merged.csv
merged.missing.filename=validation/smart_merged_validation.csv

[EDA]
eda.report.filename=/kaggle/working/intraoral_lesion/data/smart_merged/eda/eda_report.xlsx

[SEGMENT-MASKRCNN]
maskrcnn.config=/kaggle/working/intra_oral/src/segmentation/maskrcnn/maskrcnn.ini
train.dataset=/kaggle/working/intraoral_lesion/data/maskrcnn/dataset/maskrcnn.csv

[TRAIN]
augment.smart.baseroot=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART_II_AUGMENT/SMART_II_AUGMENT
augment.smartom.baseroot=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART_OM_AUGMENT/SMART_OM_AUGMENT
smart.basepath=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART II Dataset/SMART II Dataset
smartom.basepath=/kaggle/input/datasets/v18hub/intraoral-lesion/SMART-OM/SMART-OM
smart.merged.basepath=/kaggle/input/datasets/v18hub/intraoral-lesion/smart_merged/smart_merged

[SEGMENT-UNET]
unet.config = /kaggle/working/intra_oral/src/segmentation/unet/unet.ini
train.dataset = /kaggle/working/intraoral_lesion/data/unet/dataset/unet_combined_with_masks.csv