"""
train_unet.py
-------------
Fine-tunes a U-Net (pretrained ResNet34 encoder) on the annotated
SMART intraoral dataset for semantic segmentation.

Differences from Mask R-CNN:
- U-Net does pixel-wise classification (semantic segmentation)
- No bounding boxes or instance separation
- Input: RGB image → Output: pixel mask (one class per pixel)
- Loss: Dice + BCE combined (handles class imbalance)
- Evaluation: Dice coefficient + IoU per class

Pipeline
--------
1. build_data_loaders()  →  patient-wise train / val split
2. build_unet_model()    →  ResNet34 encoder + U-Net decoder
3. Training loop         →  SGD with momentum + cosine LR decay
4. Validation loop       →  Dice and IoU per class
5. Checkpointing         →  best val Dice model saved; resume supported

Dataset contract
----------------
The CSV must have at minimum:
    image_path   : absolute path to the image
    mask_path    : absolute path to the binary mask PNG
                   (generated by prepare stage from VIA/COCO JSON)
    patient_id   : used for patient-wise train/val split
    label        : lesion label (normal / opmd / variation)

Mask PNG format:
    Single-channel PNG where pixel value = class id
    0 = background, 1 = normal, 2 = opmd, 3 = variation

Usage
-----
    python train_unet.py                        # uses config defaults
    python train_unet.py --profile kaggle       # uses kaggle_config.ini
"""

import os
import argparse
import json
import sys
import time
import logging
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd

from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

from src.common.intraoral_logger import initialize_logger
from utils.load_configuration import load_config

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

# Suppress noisy libraries
logging.getLogger("PIL").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("matplotlib").setLevel(logging.WARNING)


# ══════════════════════════════════════════════════════════════════════════════
# Config
# ══════════════════════════════════════════════════════════════════════════════

class UNetConfig:
    """Parses unet.ini into typed attributes."""

    def __init__(self, cfg):
        # Training
        self.num_classes    = cfg.getint("TRAINING",  "num_classes")
        self.epochs         = cfg.getint("TRAINING",  "epochs")
        self.batch_size     = cfg.getint("TRAINING",  "batch_size")
        self.encoder_lr     = cfg.getfloat("TRAINING", "encoder_lr")
        self.decoder_lr     = cfg.getfloat("TRAINING", "decoder_lr")
        self.momentum       = cfg.getfloat("TRAINING", "momentum")
        self.weight_decay   = cfg.getfloat("TRAINING", "weight_decay")
        self.gradient_clip  = cfg.getfloat("TRAINING", "gradient_clip")
        self.val_split      = cfg.getfloat("TRAINING", "val_split")
        self.min_lr         = cfg.getfloat("TRAINING", "min_lr")
        self.log_every      = cfg.getint("TRAINING",  "log_every")
        self.val_every      = cfg.getint("TRAINING",  "val_every")
        self.loss           = cfg.get("TRAINING",     "loss")

        # Model
        self.encoder        = cfg.get("MODEL",   "encoder")
        self.pretrained     = cfg.getboolean("MODEL", "pretrained")
        inp                 = cfg.get("MODEL",   "input_size").split(",")
        self.input_size     = (int(inp[0]), int(inp[1]))
        self.dropout        = cfg.getfloat("MODEL", "dropout")

        # System
        self.device         = cfg.get("SYSTEM",  "device")
        self.num_workers    = cfg.getint("SYSTEM", "num_workers")
        self.seed           = cfg.getint("SYSTEM", "seed")

        # Paths
        self.checkpoint_dir = cfg.get("PATHS",   "checkpoint_dir")
        self.mask_output_dir = cfg.get("PATHS",  "mask_output_dir")
        self.output_dir     = cfg.get("PATHS",   "output_dir")

        # Dataset
        self.normal_dataset = cfg.get("DATASET", "normal_dataset")
        self.min_area       = cfg.getint("DATASET", "min_area")

        # Evaluation
        self.score_threshold = cfg.getfloat("EVALUATION", "score_threshold")
        self.iou_threshold   = cfg.getfloat("EVALUATION", "iou_threshold")

        # Logging
        self.save_best_model  = cfg.getboolean("LOGGING", "save_best_model")
        self.save_every_epoch = cfg.getboolean("LOGGING", "save_every_epoch")


# ══════════════════════════════════════════════════════════════════════════════
# Label mapping
# ══════════════════════════════════════════════════════════════════════════════

LABEL_CLASS_MAP = {
    "normal":    1,
    "opmd":      2,
    "variation": 3,
}
# 0 = background (no annotation)
NUM_CLASSES = 4  # background + normal + opmd + variation


# ══════════════════════════════════════════════════════════════════════════════
# Dataset
# ══════════════════════════════════════════════════════════════════════════════

class UNetDataset(Dataset):
    """
    Loads (image, mask) pairs for U-Net semantic segmentation.

    image_path : RGB image
    mask_path  : single-channel PNG where pixel value = class id
                 0=background, 1=normal, 2=opmd, 3=variation
    """

    def __init__(self, rows: pd.DataFrame, input_size: tuple):
        self.rows       = rows.reset_index(drop=True)
        self.input_size = input_size  # (H, W)

        self.img_transform = transforms.Compose([
            transforms.Resize(input_size),
            transforms.ToTensor(),
            # ImageNet normalization — matches pretrained ResNet encoder
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]
            ),
        ])

        self.mask_transform = transforms.Compose([
            transforms.Resize(
                input_size,
                interpolation=transforms.InterpolationMode.NEAREST
                # NEAREST prevents blending class values during resize
            ),
        ])

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        row       = self.rows.iloc[idx]
        img_path  = str(row["image_path"])
        mask_path = str(row["mask_path"])

        # Load image
        image = Image.open(img_path).convert("RGB")
        image = self.img_transform(image)  # [3, H, W] float tensor

        # Load mask
        mask = Image.open(mask_path).convert("L")  # grayscale
        mask = self.mask_transform(mask)
        mask = torch.as_tensor(np.array(mask), dtype=torch.long)  # [H, W] int64

        return image, mask


def collate_fn(batch):
    images, masks = zip(*batch)
    return torch.stack(images), torch.stack(masks)


# ══════════════════════════════════════════════════════════════════════════════
# Data loaders  (patient-wise split)
# ══════════════════════════════════════════════════════════════════════════════

def build_data_loaders(
    logger,
    csv_path: str,
    input_size: tuple,
    val_split: float,
    batch_size: int,
    num_workers: int,
    seed: int,
) -> tuple:
    """
    Read dataset CSV and return (train_loader, val_loader).

    Split is done on unique patient_ids so no patient appears in both
    train and val sets — prevents data leakage.
    Only rows with non-null image_path and mask_path are kept.
    """
    logger.info("Loading dataset: %s", csv_path)
    df = pd.read_csv(csv_path, dtype=str)
    logger.info("  Total CSV rows: %d", len(df))

    # Keep only rows with both image and mask paths
    df = df[df[["image_path", "mask_path"]].notnull().all(axis=1)].copy()
    logger.info("  Rows with image_path and mask_path: %d", len(df))

    if len(df) == 0:
        raise RuntimeError(
            "No valid image+mask pairs found. "
            "Run the prepare stage first to generate mask PNGs."
        )

    # Patient-wise train / val split
    if "patient_id" not in df.columns:
        raise RuntimeError("Column 'patient_id' is required for patient-wise split.")

    patient_ids = df["patient_id"].dropna().unique().tolist()
    if len(patient_ids) < 2:
        raise RuntimeError(
            f"Need at least 2 unique patient_ids for split, got {len(patient_ids)}."
        )

    # Shuffle with fixed seed
    g = torch.Generator().manual_seed(seed)
    shuffled_ids = [
        patient_ids[i]
        for i in torch.randperm(len(patient_ids), generator=g).tolist()
    ]

    n_val = max(1, int(len(shuffled_ids) * val_split))
    n_val = min(n_val, len(shuffled_ids) - 1)

    val_pids   = set(shuffled_ids[:n_val])
    train_pids = set(shuffled_ids[n_val:])

    train_df = df[df["patient_id"].isin(train_pids)].reset_index(drop=True)
    val_df   = df[df["patient_id"].isin(val_pids)].reset_index(drop=True)

    # Verify no overlap
    if set(train_df["patient_id"]) & set(val_df["patient_id"]):
        raise RuntimeError("Patient ID overlap detected between train and val sets.")
    else:
        logger.info("No overlap of patient IDs in train and val datasets.")

    logger.info(
        "  Patient-wise split: train_patients=%d (%d rows)  val_patients=%d (%d rows)",
        len(train_pids), len(train_df), len(val_pids), len(val_df),
    )

    train_ds = UNetDataset(rows=train_df, input_size=input_size)
    val_ds   = UNetDataset(rows=val_df,   input_size=input_size)

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        collate_fn=collate_fn,
        pin_memory=torch.cuda.is_available(),
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=1,
        shuffle=False,
        num_workers=num_workers,
        collate_fn=collate_fn,
        pin_memory=torch.cuda.is_available(),
    )

    logger.info("  DataLoaders ready — num_classes=%d", NUM_CLASSES)
    return train_loader, val_loader


# ══════════════════════════════════════════════════════════════════════════════
# U-Net model builder
# ══════════════════════════════════════════════════════════════════════════════

def build_unet_model(logger, num_classes: int, encoder: str,
                     pretrained: bool, device: str):
    """
    Builds a U-Net with a pretrained ResNet encoder using segmentation_models_pytorch.

    pip install segmentation-models-pytorch

    Why ResNet34 encoder?
    - Pretrained on ImageNet — general visual features available immediately
    - Encoder weights are fine-tuned with a lower LR
    - Decoder weights are trained from scratch with a higher LR
    - Skip connections pass encoder features to decoder at each resolution
    """
    try:
        import segmentation_models_pytorch as smp
    except ImportError:
        raise ImportError(
            "segmentation_models_pytorch not installed.\n"
            "Install with: pip install segmentation-models-pytorch"
        )

    model = smp.Unet(
        encoder_name=encoder,               # e.g. resnet34
        encoder_weights="imagenet" if pretrained else None,
        in_channels=3,                      # RGB input
        classes=num_classes,                # output channels = num classes
        activation=None,                    # raw logits — softmax applied in loss
    )

    device_obj = torch.device(device if torch.cuda.is_available() or device == "cpu"
                              else "cpu")
    model = model.to(device_obj)

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info("U-Net model built — encoder=%s  trainable_params=%d", encoder, n_params)
    return model, device_obj


# ══════════════════════════════════════════════════════════════════════════════
# Loss function
# ══════════════════════════════════════════════════════════════════════════════

class DiceBCELoss(nn.Module):
    """
    Combined Dice + Binary Cross-Entropy loss.

    Why combined?
    - BCE alone: dominated by background pixels when lesion is small
    - Dice alone: can be unstable with very small regions
    - Combined: BCE provides stable gradient signal, Dice improves overlap

    Dice = 2 * |A ∩ B| / (|A| + |B|)
    Perfect overlap → Dice=1 → loss=0
    No overlap → Dice=0 → loss=1
    """

    def __init__(self, num_classes: int, class_weights=None, smooth: float = 1e-6):
        super().__init__()
        self.num_classes = num_classes
        self.smooth      = smooth
        if class_weights is not None:
            weight = torch.tensor(class_weights, dtype=torch.float32)
        else:
            weight = None
        self.ce_loss = nn.CrossEntropyLoss(weight=weight)

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        """
        logits  : [B, C, H, W] — raw model output (not softmaxed)
        targets : [B, H, W]    — integer class labels per pixel
        """
        # BCE (cross-entropy) component
        ce = self.ce_loss(logits, targets)

        # Dice component — computed per class, then averaged
        probs    = torch.softmax(logits, dim=1)  # [B, C, H, W]
        dice_sum = 0.0

        for c in range(self.num_classes):
            pred_c   = probs[:, c]                            # [B, H, W]
            target_c = (targets == c).float()                 # [B, H, W]
            intersect = (pred_c * target_c).sum(dim=(1, 2))  # [B]
            union     = pred_c.sum(dim=(1, 2)) + target_c.sum(dim=(1, 2))
            dice_c    = (2 * intersect + self.smooth) / (union + self.smooth)
            dice_sum  += dice_c.mean()

        dice_loss = 1.0 - dice_sum / self.num_classes

        return ce + dice_loss


# ══════════════════════════════════════════════════════════════════════════════
# Metrics
# ══════════════════════════════════════════════════════════════════════════════

def compute_metrics(preds: torch.Tensor, targets: torch.Tensor,
                    num_classes: int) -> dict:
    """
    Compute per-class Dice and IoU, plus overall pixel accuracy.

    preds   : [B, H, W] — predicted class per pixel (argmax of logits)
    targets : [B, H, W] — ground truth class per pixel

    Dice = 2 * TP / (2*TP + FP + FN)
    IoU  = TP / (TP + FP + FN)
    Relation: Dice = 2*IoU / (1 + IoU)
    """
    results = {}
    smooth  = 1e-6

    # Pixel accuracy
    correct = (preds == targets).float().sum()
    total   = targets.numel()
    results["pixel_acc"] = (correct / total).item()

    # Per-class Dice and IoU
    dice_list = []
    iou_list  = []

    for c in range(num_classes):
        pred_c   = (preds == c).float()
        target_c = (targets == c).float()

        tp = (pred_c * target_c).sum().item()
        fp = (pred_c * (1 - target_c)).sum().item()
        fn = ((1 - pred_c) * target_c).sum().item()

        dice = (2 * tp + smooth) / (2 * tp + fp + fn + smooth)
        iou  = (tp + smooth)     / (tp + fp + fn + smooth)

        dice_list.append(dice)
        iou_list.append(iou)

        class_name = {0: "background", 1: "normal",
                      2: "opmd", 3: "variation"}.get(c, str(c))
        results[f"dice_{class_name}"] = round(dice, 4)
        results[f"iou_{class_name}"]  = round(iou,  4)

    results["mean_dice"] = round(np.mean(dice_list[1:]), 4)  # exclude background
    results["mean_iou"]  = round(np.mean(iou_list[1:]),  4)  # exclude background

    return results


# ══════════════════════════════════════════════════════════════════════════════
# Checkpoint helpers
# ══════════════════════════════════════════════════════════════════════════════

def save_checkpoint(model, optimizer, epoch: int, metrics: dict,
                    path: Path, logger) -> None:
    torch.save({
        "epoch":      epoch,
        "model":      model.state_dict(),
        "optimizer":  optimizer.state_dict(),
        "metrics":    metrics,
    }, str(path))
    logger.info("Checkpoint saved: %s", path)


def load_checkpoint(model, optimizer, path: Path, device: str, logger):
    ckpt       = torch.load(str(path), map_location=device)
    model.load_state_dict(ckpt["model"])
    optimizer.load_state_dict(ckpt["optimizer"])
    logger.info("Resumed from checkpoint: %s  (epoch %d)", path, ckpt["epoch"])
    return ckpt["epoch"], ckpt.get("metrics", {})


# ══════════════════════════════════════════════════════════════════════════════
# One training epoch
# ══════════════════════════════════════════════════════════════════════════════

def train_one_epoch(model, optimizer, criterion, loader, device,
                    epoch: int, logger, log_every: int = 10) -> dict:
    """
    Run one full pass over the training set.

    Unlike Mask R-CNN (which returns a loss dict internally),
    U-Net returns raw logits — loss must be computed externally.

    zero_grad() : resets gradients before each batch
    backward()  : computes gradients via backpropagation
    step()      : updates model weights using computed gradients
    clip_grad_norm_: prevents exploding gradients in deep networks
    """
    model.train()
    total_loss = 0.0
    n_batches  = 0
    t_start    = time.time()

    for batch_idx, (images, masks) in enumerate(loader):
        images = images.to(device)   # [B, 3, H, W]
        masks  = masks.to(device)    # [B, H, W] integer labels

        # Forward pass — returns logits [B, C, H, W]
        logits = model(images)

        # Compute combined Dice + BCE loss
        loss = criterion(logits, masks)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        total_loss += loss.item()
        n_batches  += 1

        if (batch_idx + 1) % log_every == 0 or (batch_idx + 1) == len(loader):
            avg = total_loss / n_batches
            logger.info(
                "Epoch %d | batch %d/%d | loss=%.4f | avg_loss=%.4f",
                epoch, batch_idx + 1, len(loader), loss.item(), avg,
            )

    avg_loss = total_loss / max(n_batches, 1)
    elapsed  = time.time() - t_start
    logger.info(
        "Epoch %d  train  avg_loss=%.4f  time=%.1fs",
        epoch, avg_loss, elapsed,
    )
    return {"train_loss": avg_loss}


# ══════════════════════════════════════════════════════════════════════════════
# Validation epoch
# ══════════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def validate_one_epoch(model, criterion, loader, device,
                       epoch: int, logger, num_classes: int) -> dict:
    """
    Run inference on the val set and compute:
    - Validation loss (Dice + BCE)
    - Per-class Dice and IoU
    - Overall pixel accuracy
    - Mean Dice (excluding background) — primary metric for best model selection

    @torch.no_grad() disables gradient computation during validation
    — saves memory and speeds up inference.
    """
    model.eval()
    total_loss  = 0.0
    all_preds   = []
    all_targets = []
    n_batches   = 0

    for images, masks in loader:
        images = images.to(device)
        masks  = masks.to(device)

        logits = model(images)               # [B, C, H, W]
        loss   = criterion(logits, masks)
        total_loss += loss.item()
        n_batches  += 1

        preds = logits.argmax(dim=1)         # [B, H, W] — class per pixel
        all_preds.append(preds.cpu())
        all_targets.append(masks.cpu())

    if n_batches == 0:
        logger.warning("Validation loader was empty — no metrics computed.")
        return {}

    avg_loss = total_loss / n_batches

    # Concatenate all batches
    all_preds   = torch.cat(all_preds,   dim=0)
    all_targets = torch.cat(all_targets, dim=0)

    metrics = compute_metrics(all_preds, all_targets, num_classes)
    metrics["val_loss"] = round(avg_loss, 4)

    logger.info(
        "Epoch %d  val  loss=%.4f  mean_dice=%.4f  mean_iou=%.4f  pixel_acc=%.4f",
        epoch,
        avg_loss,
        metrics["mean_dice"],
        metrics["mean_iou"],
        metrics["pixel_acc"],
    )
    logger.info(
        "  Per-class Dice — normal=%.4f  opmd=%.4f  variation=%.4f",
        metrics.get("dice_normal", 0.0),
        metrics.get("dice_opmd", 0.0),
        metrics.get("dice_variation", 0.0),
    )
    return metrics


# ══════════════════════════════════════════════════════════════════════════════
# Main training loop
# ══════════════════════════════════════════════════════════════════════════════

def train(logger, config, cfg: UNetConfig, csv_path: str) -> None:
    """
    Full U-Net training pipeline:
        1. Build data loaders (patient-wise split)
        2. Build model (ResNet34 encoder + U-Net decoder)
        3. Build loss function (Dice + BCE)
        4. Build optimizer (separate LR for encoder and decoder)
        5. Build LR scheduler (CosineAnnealing)
        6. (Optional) resume from checkpoint
        7. Epoch loop: train → validate → checkpoint
    """
    device = torch.device(
        "cuda" if torch.cuda.is_available() and cfg.device != "cpu" else "cpu"
    )
    logger.info("=" * 60)
    logger.info("  U-Net Fine-Tuning  |  device=%s", device)
    logger.info("=" * 60)

    # Data loaders
    train_loader, val_loader = build_data_loaders(
        logger=logger,
        csv_path=csv_path,
        input_size=cfg.input_size,
        val_split=cfg.val_split,
        batch_size=cfg.batch_size,
        num_workers=cfg.num_workers,
        seed=cfg.seed,
    )

    # Model
    model, device = build_unet_model(
        logger=logger,
        num_classes=cfg.num_classes,
        encoder=cfg.encoder,
        pretrained=cfg.pretrained,
        device=str(device),
    )

    # Loss
    # Class weights: background=1.0, normal=3.0, opmd=5.0, variation=4.0
    # OPMD gets highest weight because it is the rarest and most critical class
    class_weights = [1.0, 3.0, 5.0, 4.0]
    criterion = DiceBCELoss(
        num_classes=cfg.num_classes,
        class_weights=class_weights,
    ).to(device)

    # Optimizer — separate LR for encoder (pretrained) and decoder (new)
    # Encoder: lower LR — fine-tune pretrained features gently
    # Decoder: higher LR — train new upsampling layers faster
    encoder_params = list(model.encoder.parameters())
    decoder_params = [
        p for n, p in model.named_parameters()
        if "encoder" not in n
    ]

    optimizer = optim.SGD(
        [
            {"params": encoder_params, "lr": cfg.encoder_lr},
            {"params": decoder_params, "lr": cfg.decoder_lr},
        ],
        momentum=cfg.momentum,
        weight_decay=cfg.weight_decay,
    )

    # CosineAnnealingLR — smoothly decays LR from initial to min_lr over all epochs
    # Formula: lr_t = min_lr + 0.5*(lr_0 - min_lr)*(1 + cos(pi*t/T_max))
    # This helps the model converge more stably into a good minimum
    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=cfg.epochs,
        eta_min=cfg.min_lr,
    )

    # Checkpoint setup
    checkpoint_dir = Path(cfg.checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    best_ckpt_path = checkpoint_dir / "best.pth"
    last_ckpt_path = checkpoint_dir / "last.pth"

    start_epoch  = 1
    best_dice    = 0.0
    history      = []

    # Resume from last checkpoint if available
    if last_ckpt_path.exists():
        start_epoch, prev_metrics = load_checkpoint(
            model, optimizer, last_ckpt_path, str(device), logger
        )
        best_dice   = prev_metrics.get("mean_dice", 0.0)
        start_epoch += 1
        logger.info(
            "Resuming from epoch %d  (best mean_dice=%.4f)",
            start_epoch, best_dice,
        )
    else:
        logger.info("No checkpoint found — starting fresh training.")

    # Epoch loop
    for epoch in range(start_epoch, cfg.epochs + 1):
        logger.info("\n--- Epoch %d / %d ---", epoch, cfg.epochs)

        # Train
        train_metrics = train_one_epoch(
            model, optimizer, criterion, train_loader,
            device, epoch, logger, log_every=cfg.log_every,
        )

        # LR step
        scheduler.step()
        current_lrs = [pg["lr"] for pg in optimizer.param_groups]
        logger.info(
            "  LR after step: encoder=%.2e  decoder=%.2e",
            current_lrs[0], current_lrs[1],
        )

        # Validate
        val_metrics = {}
        if epoch % cfg.val_every == 0 or epoch == cfg.epochs:
            val_metrics = validate_one_epoch(
                model, criterion, val_loader, device,
                epoch, logger, num_classes=cfg.num_classes,
            )

        # Save last checkpoint (enables resume)
        all_metrics = {**train_metrics, **val_metrics}
        save_checkpoint(model, optimizer, epoch, all_metrics, last_ckpt_path, logger)

        # Save best checkpoint based on mean Dice (excludes background)
        # Mean Dice is preferred over accuracy due to class imbalance
        current_dice = val_metrics.get("mean_dice", 0.0)
        if val_metrics and current_dice > best_dice:
            best_dice = current_dice
            save_checkpoint(
                model, optimizer, epoch, all_metrics, best_ckpt_path, logger
            )
            logger.info(
                "  New best mean_dice=%.4f — saved to %s",
                best_dice, best_ckpt_path,
            )

        history.append({"epoch": epoch, **all_metrics})

    # Save training history
    history_path = checkpoint_dir / "training_history.json"
    with open(history_path, "w") as f:
        json.dump(history, f, indent=2)
    logger.info("Training history saved: %s", history_path)
    logger.info("Training complete. Best mean_dice=%.4f", best_dice)


# ══════════════════════════════════════════════════════════════════════════════
# Path utilities (mirrors train_maskrcnn.py)
# ══════════════════════════════════════════════════════════════════════════════

def update_merged_df_paths(smart_base_path, smartom_base_path, df):
    """Prepend base paths to relative image/mask paths in merged dataset."""
    mask1 = df["source"] == "smart_II"
    mask2 = df["source"] == "smart_om"
    for col in ["image_path", "mask_path", "json_file"]:
        if col in df.columns:
            df.loc[mask1, col] = (
                smart_base_path + "/" + df.loc[mask1, col].astype(str)
            )
            df.loc[mask2, col] = (
                smartom_base_path + "/" + df.loc[mask2, col].astype(str)
            )
    return df


def update_paths(base_path, df):
    """Prepend base path to relative paths in augmented dataset."""
    for col in ["image_path", "mask_path", "json_file"]:
        if col in df.columns:
            df[col] = (
                base_path + "/" + df[col].astype(str).where(df[col].notna())
            )
    return df


def get_dataset_path(logger, config, cfg: UNetConfig) -> str:
    """
    Build the training CSV based on which dataset provides Normal images.

    Options (from unet.ini [DATASET] normal_dataset):
        SMART_II  : Normal from SMART_II only; OPMD+Variation from both
        SMART_OM  : Normal from SMART_OM only; OPMD+Variation from both
        BOTH      : All labels from both datasets
    """
    smart_merged_basepath = config.get("TRAIN", "smart.merged.basepath")
    smart_base            = config.get("TRAIN", "smart.basepath")
    smartom_base          = config.get("TRAIN", "smartom.basepath")
    augment_smart_base    = config.get("TRAIN", "augment.smart.baseroot")
    augment_smartom_base  = config.get("TRAIN", "augment.smartom.baseroot")

    merged_data_path = (
        f"{smart_merged_basepath}/"
        f"{config.get('SMART_MERGED', 'merged.coco.output.filename')}"
    )
    aug_smart_csv = (
        f"{augment_smart_base}/"
        f"{config.get('AUGMENT_SMART', 'augment.patient.coco.metadata.filename')}"
    )
    aug_smartom_csv = (
        f"{augment_smartom_base}/"
        f"{config.get('AUGMENT_SMARTOM', 'augment.patient.coco.metadata.filename')}"
    )

    dataset = pd.DataFrame()

    # Load merged dataset
    if Path(merged_data_path).exists():
        merged_df = pd.read_csv(merged_data_path)
        merged_df = update_merged_df_paths(smart_base, smartom_base, merged_df)
        logger.info("Loaded merged data: %s", merged_df.shape)
    else:
        raise FileNotFoundError(f"Merged dataset not found: {merged_data_path}")

    # Load augmented SMART-II
    if Path(aug_smart_csv).exists():
        aug_s = pd.read_csv(aug_smart_csv)
        aug_s = update_paths(augment_smart_base, aug_s)
        dataset = pd.concat([dataset, aug_s])
        logger.info("Added SMART-II augmented: %s", aug_s.shape)

    # Load augmented SMART-OM
    if Path(aug_smartom_csv).exists():
        aug_om = pd.read_csv(aug_smartom_csv)
        aug_om = update_paths(augment_smartom_base, aug_om)
        dataset = pd.concat([dataset, aug_om])
        logger.info("Added SMART-OM augmented: %s", aug_om.shape)

    # Filter by normal_dataset setting
    if cfg.normal_dataset == "SMART_II":
        temp = merged_df[
            (merged_df.source == "smart_II")
            | ((merged_df.source == "smart_om") & (merged_df.label != "normal"))
        ]
        dataset = pd.concat([dataset, temp])
    elif cfg.normal_dataset == "SMART_OM":
        temp = merged_df[
            (merged_df.source == "smart_om")
            | ((merged_df.source == "smart_II") & (merged_df.label != "normal"))
        ]
        dataset = pd.concat([dataset, temp])
    elif cfg.normal_dataset == "BOTH":
        dataset = pd.concat([dataset, merged_df])

    logger.info("Final dataset shape: %s", dataset.shape)

    # Save training CSV
    train_csv_path = config.get("SEGMENT-UNET", "train.dataset")
    Path(train_csv_path).parent.mkdir(parents=True, exist_ok=True)
    dataset = dataset.replace([np.nan, "nan", "NaN"], None)
    # Keep only rows with both image and mask
    df = dataset[dataset[["image_path", "mask_path"]].notnull().all(axis=1)].copy()
    logger.info("Rows with image_path and mask_path: %d", len(df))
    df.to_csv(train_csv_path, index=False)

    return train_csv_path


def get_configpath():
    parser = argparse.ArgumentParser(description="U-Net training script")
    parser.add_argument("-p", "--profile")
    args       = parser.parse_args()
    config_path = "config/config.ini"
    if args.profile and args.profile.lower() == "kaggle":
        config_path = "config/kaggle_config.ini"
    return config_path


# ══════════════════════════════════════════════════════════════════════════════
# Entry point
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    config_path = get_configpath()
    config      = load_config(config_path)
    logger      = initialize_logger(config=config)
    unet_cfg    = load_config(config.get("SEGMENT-UNET", "unet.config"))
    cfg         = UNetConfig(unet_cfg)
    csv_path    = config.get("SEGMENT-UNET", "train.dataset")
    train(logger=logger, config=config, cfg=cfg, csv_path=csv_path)


"""
Interpretation of U-Net training results:

train_loss: Combined Dice + BCE loss over training set.
val_loss   : Same loss on validation set — watch for gap between train/val
             (large gap = overfitting).

mean_dice  : Mean Dice score across lesion classes (normal, opmd, variation),
             excluding background. PRIMARY metric for model selection.
             0.0 = no overlap, 1.0 = perfect overlap.

mean_iou   : Mean Intersection-over-Union across lesion classes.
             Related to Dice: IoU = Dice / (2 - Dice)
             Stricter than Dice.

pixel_acc  : Fraction of correctly classified pixels.
             WARNING: misleading metric — background pixels dominate.
             A model predicting background everywhere can get 90%+ accuracy.
             Always report Dice/IoU alongside pixel accuracy.

dice_opmd  : Dice score specifically for OPMD class.
             Most critical class clinically — low dice_opmd means the model
             is missing potentially malignant lesions.
             OPMD has fewest training samples → expect lowest Dice initially.

dice_variation: Dice for variation class.

dice_normal: Dice for normal tissue.

LR after step: Cosine-annealed learning rates for encoder and decoder.
               encoder LR starts lower (pretrained weights preserved).
               decoder LR starts higher (new weights need faster learning).

If dice_opmd = 0.0 after several epochs:
    → Model is ignoring OPMD class entirely due to class imbalance
    → Increase class_weights for OPMD (e.g. from 5.0 to 8.0)
    → Increase augmentation count for OPMD images
    → Check that mask PNGs have correct pixel values for OPMD (value=2)
"""